### ISSUE TITLE
File not found 'pure-ethernet-structure-2-0.tree'

### ISSUE THREAD

**Issue by Jothi-upashana** [openBackhaul/pureEthernetStructure#18]
In Pure Ethernet Structure 2.0.0-tsp.d.t, there is no 'pure-ethernet-structure-2-0.tree' file found.
Have pure-ethernet-structure-2-0.yang and core-model-1-4.yang in repository.

Is there a way to get 'pure-ethernet-structure-2-0.tree' from repository?

**Comment by openBackhaul** [comment]
No sorry, was just sporadically provided.
