### ISSUE TITLE
clearingThresholdCrossAlarmsIsOn to be replaced by RPC

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/pureEthernetStructure#23]
clearingThresholdCrossAlarmsIsOn is not a real configuration parameter, because it will always flip back to false.
RPC would be a better implementation.

See AirInterface modeling as a reference.

**Comment by demx8as6** [comment]
See also: 
 * https://github.com/openBackhaul/hybridMwStructure/issues/29 
 * https://github.com/openBackhaul/airInterface/issues/50

**Comment by openBackhaul** [comment]
**Decision during the 5G-xhaul call on 9th of August 2023:**

The PureEthernetStructure UML model must be aligned with the latest decisions done for the AirInterface.

1. The attribute "clearingThresholdCrossAlarmsIsOn" must be removed from the configuration object class.
2. The AirInterface RPC "clearThresholdCrossAlarm" should be added - modified for PureEthernetStructure. 

(SIAE and Nokia agreed upfront on 25th of July 2023.)

**Comment by openBackhaul** [comment]
Fixed with PureEthernetStructure_2.0.0-tsi.230907.1715+yang.1
