### ISSUE TITLE
Mandatory Attributes

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/pureEthernetStructure#24]
The latest UML2YANG tool will include mandatory substatement to attributes that has "Multiplicity 1 + no default values defined".
The following attributes which are formerly optional will be changed to mandatory in the upcoming YANG.

Further , if an attribute is decided to be optional , we shall handle it in the UML modelling by either introducing a default value or by modifying the Multiplicity to 0..1.

| S.No | Grouping/Datatype                    | Attribute              | Mandatory | Optional |
|------|--------------------------------------|------------------------|-----------|----------|
| 1    | object-creation-notification         | object-id-ref          |           |          |
| 2    | object-deletion-notification         | object-id-ref          |           |          |
| 3    | attribute-value-changed-notification | object-id-ref          |           |          |
| 4    | current-performance                  | granularity-period     |           |          |
| 5    | historical-performance               | granularity-period     |           |          |
| 6    |                                      | period-end-time        |           |          |
| 7    | g-826-threshold-cross-alarm-type     | g-826-value-kind       |           |          |
| 8    |                                      | granularity-period     |           |          |
| 9    | segment-status-type                  | segment-status-type-id |

**Comment by openBackhaul** [comment]
**Decision during the 5G-xhaul call on 6th of September 2023:**

The attributes marked as "Mandatory" shall stick with multiplicity [1].

The attributes marked as "Optional" shall change to multiplicity [0..1] and get a default value.

| S.No | Grouping/Datatype                    | Attribute              | Mandatory | Optional |
|------|--------------------------------------|------------------------|-----------|----------|
| 1    | object-creation-notification         | object-id-ref          | X         |          |
| 2    | object-deletion-notification         | object-id-ref          | X         |          |
| 3    | attribute-value-changed-notification | object-id-ref          | X         |          |
| 4    | current-performance                  | granularity-period     | X 1)      |          |
| 5    | historical-performance               | granularity-period     | X 1)      |          |
| 6    |                                      | period-end-time        | X 1)      |          |
| 7    | g-826-threshold-cross-alarm-type     | g-826-value-kind       | X 1)      |          |
| 8    |                                      | granularity-period     | X 1)      |          |
| 9    | segment-status-type                  | segment-status-type-id | X 1)      |          |

1\) It is a key attribute

**Comment by openBackhaul** [comment]
Fixed with PureEthernetStructure_2.0.0-tsi.230907.1715+yang.1
